apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80          # Service port
      targetPort: 80    # Container port
      nodePort: 30080   # Fixed external NodePort (optional, can remove for auto-assignment)
  type: NodePort
