apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
spec:
  group: external-secrets.io
  names:
    kind: ExternalSecret
    plural: externalsecrets
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
