apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: github-secret-store
spec:
  provider:
    github:
      auth:
        tokenSecretRef:
          name: github-secret-store
          key: token
      repository: https://github.com/ShahzaibRao/homeops.git
