---
- name: Create namespace for ArgoCD
  become: yes
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: Install ArgoCD components
  become: yes
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    namespace: argocd

- name: Wait for ArgoCD pods to be ready
  become: yes
  shell: |
    kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd
  register: argocd_ready
  changed_when: false

- name: Expose ArgoCD server as LoadBalancer (optional)
  become: yes
  shell: |
    kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
  ignore_errors: true

- name: Retrieve initial ArgoCD admin password
  become: yes
  shell: |
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d
  register: argocd_password

- debug:
    msg: "ArgoCD Admin Password: {{ argocd_password.stdout }}"

- name: Deploy initial GitOps Application (optional)
  become: yes
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'app.yaml.j2') }}"
