apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: cloudflared
  ports:
    - port: 80
      targetPort: 8080
