apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
    - name: internal-cluster
      port: 8201
      targetPort: 8201
      protocol: TCP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault