apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  template:
    spec:
      serviceAccountName: vault
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for Vault to be ready
              until vault status -address=http://vault:8200; do
                echo "Waiting for Vault to be ready..."
                sleep 5
              done
              
              # Initialize Vault if not already initialized
              if ! vault status -address=http://vault:8200 | grep -q "Initialized.*true"; then
                echo "Initializing Vault..."
                vault operator init -address=http://vault:8200 -key-shares=5 -key-threshold=3 > /tmp/vault-init.txt
                
                # Extract unseal keys and root token
                UNSEAL_KEY_1=$(grep "Unseal Key 1:" /tmp/vault-init.txt | awk '{print $4}')
                UNSEAL_KEY_2=$(grep "Unseal Key 2:" /tmp/vault-init.txt | awk '{print $4}')
                UNSEAL_KEY_3=$(grep "Unseal Key 3:" /tmp/vault-init.txt | awk '{print $4}')
                ROOT_TOKEN=$(grep "Initial Root Token:" /tmp/vault-init.txt | awk '{print $4}')
                
                # Store unseal keys in Kubernetes secrets
                kubectl create secret generic vault-unseal-keys \
                  --from-literal=key1="$UNSEAL_KEY_1" \
                  --from-literal=key2="$UNSEAL_KEY_2" \
                  --from-literal=key3="$UNSEAL_KEY_3" \
                  --from-literal=root-token="$ROOT_TOKEN" \
                  -n vault \
                  --dry-run=client -o yaml | kubectl apply -f -
                  
                echo "Vault initialized successfully"
                echo "Unseal keys and root token stored in vault-unseal-keys secret"
              else
                echo "Vault is already initialized"
              fi
          env:
            - name: VAULT_ADDR
              value: "http://vault:8200"
          restartPolicy: OnFailure
      backoffLimit: 6
  backoffLimit: 1