apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: github-store
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
    - secretKey: tunnel-credentials
      remoteRef:
        key: CLOUDFLARE_TUNNEL_CREDENTIALS_JSON_B64
