apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-store
  namespace: external-secrets
spec:
  provider:
    github:
      auth:
        secretRef:
          accessTokenSecretRef:
            name: github-secret-store
            key: token
      repository: ShahzaibRao/homeops
