apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: infra
type: Opaque
stringData:
  tunnel.json: |
    ${CLOUDFLARE_TUNNEL_CREDENTIALS}
  config.yml: |
    tunnel: argocd-tunnel
    credentials-file: /etc/cloudflared/tunnel.json
    ingress:
      - hostname: argocd.raoshahzaib.site
        service: https://argocd-server.argocd.svc.cluster.local:443
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args: ["tunnel", "--no-autoupdate", "run", "--config", "/etc/cloudflared/config.yml"]
          volumeMounts:
            - name: cloudflared-secret
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared-secret
          secret:
            secretName: cloudflared-secret
