{{- if .Values.initJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vault.fullname" . }}-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "vault.serviceAccountName" . }}
      containers:
        - name: vault-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for Vault to be ready
              until vault status -address=http://{{ include "vault.fullname" . }}:8200; do
                echo "Waiting for Vault to be ready..."
                sleep 5
              done
              
              # Initialize Vault if not already initialized
              if ! vault status -address=http://{{ include "vault.fullname" . }}:8200 | grep -q "Initialized.*true"; then
                echo "Initializing Vault..."
                vault operator init -address=http://{{ include "vault.fullname" . }}:8200 -key-shares=5 -key-threshold=3 > /tmp/vault-init.txt
                
                # Extract unseal keys and root token
                UNSEAL_KEY_1=$(grep "Unseal Key 1:" /tmp/vault-init.txt | awk '{print $4}')
                UNSEAL_KEY_2=$(grep "Unseal Key 2:" /tmp/vault-init.txt | awk '{print $4}')
                UNSEAL_KEY_3=$(grep "Unseal Key 3:" /tmp/vault-init.txt | awk '{print $4}')
                ROOT_TOKEN=$(grep "Initial Root Token:" /tmp/vault-init.txt | awk '{print $4}')
                
                # Store unseal keys in Kubernetes secrets
                kubectl create secret generic {{ include "vault.fullname" . }}-unseal-keys \
                  --from-literal=key1="$UNSEAL_KEY_1" \
                  --from-literal=key2="$UNSEAL_KEY_2" \
                  --from-literal=key3="$UNSEAL_KEY_3" \
                  --from-literal=root-token="$ROOT_TOKEN" \
                  -n {{ .Release.Namespace }} \
                  --dry-run=client -o yaml | kubectl apply -f -
                  
                echo "Vault initialized successfully"
                echo "Unseal keys and root token stored in {{ include "vault.fullname" . }}-unseal-keys secret"
              else
                echo "Vault is already initialized"
              fi
          env:
            {{- range $key, $value := .Values.initJob.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          restartPolicy: OnFailure
      backoffLimit: {{ .Values.initJob.backoffLimit }}
  backoffLimit: 1
{{- end -}}