name: Deploy K3s with Ansible

on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'     # ✅ Only trigger when something inside ansible/ changes
  workflow_dispatch:      # ✅ Still allow manual runs

jobs:
  deploy:
    runs-on: self-hosted   # ✅ Use your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts (optional)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventory.ini k3s-deploy.yml
